# Generated by Django 3.2.9 on 2021-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsaVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(default='VN', max_length=3, verbose_name='Document type')),
                ('doc_country', models.CharField(default='USA', max_length=3, verbose_name='Document country')),
                ('surname', models.CharField(default='MUSTAINE', max_length=25, verbose_name='Surname(s)')),
                ('givenname', models.CharField(default='JOHN', max_length=25, verbose_name='Given name(s)')),
                ('doc_number', models.CharField(default='123456789', max_length=9, verbose_name='Document number')),
                ('nationality', models.CharField(default='CAN', max_length=4, verbose_name='Nationality')),
                ('birthdate', models.CharField(default='991220', max_length=6, verbose_name='Birth date')),
                ('genre', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='F', max_length=1, verbose_name='Genre')),
                ('doc_exp_date', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='F', max_length=1, verbose_name='Expiry date')),
                ('optional_data', models.CharField(blank=True, default='B3XLC000FD142955', max_length=16, verbose_name='Optional data')),
                ('photo_document', models.ImageField(null=True, upload_to='media/cfg/usa/usavisa/%d', verbose_name='Photo iD')),
                ('remove_bg', models.BooleanField(default=False, verbose_name='Remove background [BETA]')),
                ('get_exif_info', models.ImageField(null=True, upload_to='media/cfg/exif_tool/', verbose_name='Load image  EXIF')),
                ('background_image', models.ImageField(null=True, upload_to='media/cfg/background_image/', verbose_name='Загрузить фон')),
            ],
            options={
                'verbose_name': 'Usa Visa',
                'verbose_name_plural': 'Usa Visas',
            },
        ),
    ]
