# Generated by Django 3.2.9 on 2021-11-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statecardusa',
            name='background_image',
            field=models.ImageField(null=True, upload_to='cfg/background_image/', verbose_name='Загрузить фон'),
        ),
        migrations.AlterField(
            model_name='statecardusa',
            name='get_exif_info',
            field=models.ImageField(null=True, upload_to='cfg/exif_tool/', verbose_name='Загрузить фото для копирования EXIF'),
        ),
        migrations.AlterField(
            model_name='statecardusa',
            name='passport_card_number',
            field=models.CharField(default='C000091', max_length=9, verbose_name='Passpord Card Num'),
        ),
        migrations.AlterField(
            model_name='statecardusa',
            name='photo_document',
            field=models.ImageField(null=True, upload_to='cfg/usa/photo_id/', verbose_name='Photo iD'),
        ),
    ]
