# Generated by Django 3.2.9 on 2021-11-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0002_usavisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usavisa',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='media/cfg/usa/background_image/', verbose_name='Загрузить фон'),
        ),
        migrations.AlterField(
            model_name='usavisa',
            name='birthdate',
            field=models.CharField(default=991220, max_length=6, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='usavisa',
            name='doc_exp_date',
            field=models.CharField(default=991220, max_length=6, verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='usavisa',
            name='get_exif_info',
            field=models.ImageField(blank=True, upload_to='media/cfg/usa/exif_tool/', verbose_name='Load image  EXIF'),
        ),
        migrations.AlterField(
            model_name='usavisa',
            name='photo_document',
            field=models.ImageField(blank=True, upload_to='media/cfg/usa/usavisa/', verbose_name='Photo iD'),
        ),
    ]
