# Generated by Django 3.2.9 on 2021-11-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0003_auto_20211108_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usavisa',
            name='birthdate',
            field=models.CharField(default='991220', max_length=6, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='usavisa',
            name='doc_exp_date',
            field=models.CharField(default='991220', max_length=6, verbose_name='Expiry date'),
        ),
    ]
