# Generated by Django 4.0 on 2022-01-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='user',
            new_name='username',
        ),
    ]
